version: "3.11"

services:
  #new app (angular_app)
  angular_app:
    container_name: angular_app
    image: pee-angular_app:1.0.0
    build: ./sistema/
    ports:
      - 4200:4200
    depends_on:
      - java_app
  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - HOST= 0.0.0.0
      - PORT= 4000
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER: root
      MYSQL_DB: base
    volumes:
      -./mysql-data:/var/lib/mysql