version: "3.11"

services:
  #new app (angular_app)
  angular_app:
    container_name: angular_app
    image: pee-angular_app:1.0.0
    build: 
      context: ./sistema
      dockerfile: dockerfile
    ports:
      - "8000:4200"
    depends_on:
      - java_app
  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "4000:4000"
    environment:
      - HOST= 0.0.0.0
      - PORT= 4000
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: sharon
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: sharon
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: